# -*- coding: utf-8 -*-
import io, sys

PATH = "E:/Xiuxian/taixuanzongmenlu/main.gd"
with io.open(PATH, "r", encoding="utf-8", newline="") as f:
    src = f.read()

reps = []  # (old, new, expected_count)

# 1) const 页名 -> 5 Tab
reps.append((
    'const 页名 := ["弟子", "待抉择", "御兽", "纪事"]',
    'const 页名 := ["宗门", "弟子", "御兽", "历练", "纪事"]',
    1,
))

# 2) 移除 页控 声明
reps.append((
    'var _差事提示: String = ""\nvar 页控: Dictionary = {}',
    'var _差事提示: String = ""',
    1,
))

# 3) 新增实例变量（接在 _灰锁原文本 之后）
reps.append((
    'var _灰锁原文本: Dictionary = {}',
    'var _灰锁原文本: Dictionary = {}\n'
    '# 整页切换架构（UI整改「三」第二批）\n'
    'var 内容区: Control = null            # 固定内容区锚点（顶栏下/底栏上），承载当前页容器\n'
    'var 当前页容器: ScrollContainer = null  # 当前整页根（ScrollContainer+VBox），切换时 queue_free\n'
    'var 当前页名: String = ""              # 当前核心 Tab 名（用于刷新/入门指引判定）\n'
    'var 当前页持久节点: Array = []          # 当前页持有的持久 VBox（切换前先卸下，避免被 queue_free 误杀）\n'
    'var _二级页: String = ""                # 当前二级页名（""=核心页；非空前主导航仍高亮宗门）\n'
    'var _弟子二级tab: int = 0               # 弟子页二级 Tab：0=名录 / 1=接引（跨切换保留）\n'
    'var 调试图标: Button = null             # 顶栏角落：推演中心（Debug 可见）\n'
    'var 设置图标: Button = null             # 顶栏角落：设置（存读/新游戏）\n'
    'var _宗门网格入口: Dictionary = {}      # 名 -> 快捷入口按钮（灰锁用）\n'
    'var 差事列: VBoxContainer = null        # 差事二级页列表列（刷新用）',
    1,
))

# 4) 主布局 / 中区 / 中区内容 / 底部区 -> 顶栏 + 内容区 + 底部区
reps.append((
    '\t# 主垂直布局：占满目标条以下、屏幕底部边距区域\n'
    '\tvar 主布局 := VBoxContainer.new()\n'
    '\t主布局.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)\n'
    '\t主布局.offset_top = 48    # 顶部预留 48px 给常驻目标条（§5.1）\n'
    '\t主布局.offset_left = 8\n'
    '\t主布局.offset_right = -8\n'
    '\t主布局.offset_bottom = -8\n'
    '\t主布局.add_theme_constant_override("separation", 6)\n'
    '\tadd_child(主布局)\n'
    '\n'
    '\t# 中部可滚动内容区（占满主布局剩余空间）\n'
    '\tvar 中区 := ScrollContainer.new()\n'
    '\t中区.size_flags_horizontal = Control.SIZE_EXPAND_FILL\n'
    '\t中区.size_flags_vertical = Control.SIZE_EXPAND_FILL\n'
    '\t主布局.add_child(中区)\n'
    '\n'
    '\tvar 中区内容 := VBoxContainer.new()\n'
    '\t中区内容.size_flags_horizontal = Control.SIZE_EXPAND_FILL\n'
    '\t中区内容.size_flags_vertical = Control.SIZE_EXPAND_FILL\n'
    '\t中区内容.add_theme_constant_override("separation", 6)\n'
    '\t中区.add_child(中区内容)\n'
    '\n'
    '\t# 底部固定栏：TabBar + 详情面板（不再随中部内容滚动）\n'
    '\tvar 底部区 := VBoxContainer.new()\n'
    '\t底部区.size_flags_horizontal = Control.SIZE_EXPAND_FILL\n'
    '\t底部区.custom_minimum_size = Vector2(0, 180)\n'
    '\t主布局.add_child(底部区)\n',
    '\t# 主垂直布局：占满目标条以下、屏幕底部边距区域\n'
    '\tvar 主布局 := VBoxContainer.new()\n'
    '\t主布局.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)\n'
    '\t主布局.offset_top = 48    # 顶部预留 48px 给常驻目标条（§5.1）\n'
    '\t主布局.offset_left = 8\n'
    '\t主布局.offset_right = -8\n'
    '\t主布局.offset_bottom = -8\n'
    '\t主布局.add_theme_constant_override("separation", 6)\n'
    '\tadd_child(主布局)\n'
    '\n'
    '\t# 顶栏（固定，不随页面切换销毁）：掌教标题 + 状态带 + 角落图标\n'
    '\tvar 顶栏 := VBoxContainer.new()\n'
    '\t顶栏.size_flags_horizontal = Control.SIZE_EXPAND_FILL\n'
    '\t顶栏.add_theme_constant_override("separation", 4)\n'
    '\t主布局.add_child(顶栏)\n'
    '\n'
    '\t# 内容区锚点（固定）：顶栏下、底栏上，承载当前整页容器\n'
    '\t内容区 = Control.new()\n'
    '\t内容区.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)\n'
    '\t内容区.mouse_filter = Control.MOUSE_FILTER_IGNORE\n'
    '\t主布局.add_child(内容区)\n'
    '\n'
    '\t# 底部固定栏：TabBar + 详情面板（不再随中部内容滚动）\n'
    '\tvar 底部区 := VBoxContainer.new()\n'
    '\t底部区.size_flags_horizontal = Control.SIZE_EXPAND_FILL\n'
    '\t底部区.custom_minimum_size = Vector2(0, 180)\n'
    '\t主布局.add_child(底部区)\n',
    1,
))

# 5) 顶栏头 + 角落图标 + 离山面板（独立弹窗）
reps.append((
    '\t# 顶部标题 + 状态面板\n'
    '\tvar 掌教标题 := Button.new()\n'
    '\t掌教标题.text = "《太玄宗门录》· 掌教治宗"\n'
    '\t掌教标题.flat = true\n'
    '\t掌教标题.add_theme_font_size_override("font_size", FONT_PANEL_B)\n'
    '\t掌教标题.add_theme_color_override("font_color", 暗金)\n'
    '\t掌教标题.pressed.connect(_on_掌教点击彩蛋)\n'
    '\t中区内容.add_child(掌教标题)\n'
    '\tvar 别名 := Label.new()\n'
    '\t别名.text = "又名：开局接手太玄宗"\n'
    '\t别名.add_theme_font_size_override("font_size", FONT_AUX)\n'
    '\t别名.add_theme_color_override("font_color", 宣纸亮)\n'
    '\t中区内容.add_child(别名)\n'
    '\t状态栏 = Label.new()\n'
    '\t状态栏.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART\n'
    '\t状态栏.mouse_filter = Control.MOUSE_FILTER_IGNORE   # 让点击穿透到状态面板，供入门指引步骤①Hook\n'
    '\tvar 状态面板: PanelContainer = 新面板("")\n'
    '\t状态面板.get_child(0).add_child(状态栏)\n'
    '\t状态面板.add_theme_stylebox_override("panel", _暗墨面板())\n'
    '\t状态栏.add_theme_color_override("font_color", 暗金)\n'
    '\t中区内容.add_child(状态面板)\n'
    '\t入门指引_状态面板 = 状态面板\n'
    '\n'
    '\t# 按钮行（紧凑，竖屏 480 宽可分两行）\n'
    '\tvar 行 := HBoxContainer.new()\n'
    '\t行.add_theme_constant_override("separation", 6)\n'
    '\t中区内容.add_child(行)\n'
    '\tvar 推演 := Button.new(); 推演.text = "推演汇总"; 行.add_child(推演); 推演.pressed.connect(_on_推演)\n'
    '\t入门指引_推演按钮 = 推演\n'
    '\tvar 招收 := Button.new(); 招收.text = "开启接引大典"; 行.add_child(招收); 招收.pressed.connect(_on_测灵根)\n'
    '\t入门指引_招收按钮 = 招收\n'
    '\tvar 殿阁 := Button.new(); 殿阁.text = "殿阁总览"; 行.add_child(殿阁); 殿阁.pressed.connect(_on_殿阁总览)\n'
    '\t入门指引_殿阁按钮 = 殿阁\n'
    '\tvar 行二 := HBoxContainer.new()\n'
    '\t行二.add_theme_constant_override("separation", 6)\n'
    '\t中区内容.add_child(行二)\n'
    '\tvar 快进 := Button.new(); 快进.text = "御兽快进"; 行二.add_child(快进); 快进.pressed.connect(_on_快进)\n'
    '\tvar 存 := Button.new(); 存.text = "存档"; 行二.add_child(存); 存.pressed.connect(_on_存档)\n'
    '\tvar 读 := Button.new(); 读.text = "读档"; 行二.add_child(读); 读.pressed.connect(_on_读档)\n'
    '\t# 调试行：灰模战斗入口 + 测试工具（ADR-003 D7 调试工具）\n'
    '\tvar 行三 := HBoxContainer.new()\n'
    '\t行三.add_theme_constant_override("separation", 6)\n'
    '\t中区内容.add_child(行三)\n'
    '\tvar 调试 := Button.new(); 调试.text = "调试战斗"; 行三.add_child(调试); 调试.pressed.connect(_on_调试战斗)\n'
    '\tvar 历练 := Button.new(); 历练.text = "历练征途"; 行三.add_child(历练); 历练.pressed.connect(_on_历练)\n'
    '\t入门指引_历练按钮 = 历练\n'
    '\tvar 坊市 := Button.new(); 坊市.text = "坊市"; 行三.add_child(坊市); 坊市.pressed.connect(_on_坊市)\n'
    '\t入门指引_坊市按钮 = 坊市\n'
    '\tvar 差事 := Button.new(); 差事.text = "差事"; 行三.add_child(差事); 差事.pressed.connect(_on_差事)\n'
    '\t入门指引_差事按钮 = 差事\n'
    '\t# 强制触发征伐奇遇：调试专用，release 导出自动隐藏（OS.is_debug_build 包裹 add_child，不留死代码）\n'
    '\tvar 行四 := HBoxContainer.new()\n'
    '\t行四.add_theme_constant_override("separation", 6)\n'
    '\t中区内容.add_child(行四)\n'
    '\tif OS.is_debug_build():\n'
    '\t\tvar 强制征伐 := Button.new(); 强制征伐.text = "强制征伐"\n'
    '\t\t行四.add_child(强制征伐); 强制征伐.pressed.connect(_on_强制征伐)\n'
    '\t\tvar 重置入门指引 := Button.new(); 重置入门指引.text = "重置入门指引"\n'
    '\t\t行四.add_child(重置入门指引); 重置入门指引.pressed.connect(_on_重置入门指引)\n'
    '\t\tvar 推演7 := Button.new(); 推演7.text = "推演7天"\n'
    '\t\t行四.add_child(推演7); 推演7.pressed.connect(_on_推演七日)\n'
    '\t\tvar 强制天品 := Button.new(); 强制天品.text = "强制天品"\n'
    '\t\t行四.add_child(强制天品); 强制天品.pressed.connect(_on_强制天品)\n'
    '\t\tvar 强制聚气丹 := Button.new(); 强制聚气丹.text = "强制聚气丹"\n'
    '\t\t行四.add_child(强制聚气丹); 强制聚气丹.pressed.connect(_on_强制聚气丹)\n'
    '\tvar 新游戏 := Button.new(); 新游戏.text = "新游戏"\n'
    '\t行四.add_child(新游戏); 新游戏.pressed.connect(_on_新游戏)\n'
    '\tvar 快进年 := Button.new(); 快进年.text = "推演1年"\n'
    '\t行四.add_child(快进年); 快进年.pressed.connect(_on_推荐一年)\n'
    '\n'
    '\t# 战报面板（登录推演汇总 → 三层结构：总览/重大事件/琐事折叠）\n'
    '\t离山面板 = 新面板("✦ 离山汇总（你离开期间）")\n'
    '\t离山内容区 = 离山面板.get_child(0) as VBoxContainer  # 新面板返回的 VBox\n'
    '\t离山面板.custom_minimum_size = Vector2(0, 140)\n'
    '\t中区内容.add_child(离山面板)\n'
    '\t# 战报 Label 保留作兼容降级显示（旧存档/无结构化数据时用）\n'
    '\t战报 = Label.new()\n'
    '\t战报.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART\n'
    '\t战报.visible = false   # 默认隐藏，新UI优先\n',
    '\t# 顶栏：掌教标题 + 别名 + 状态带（固定不滚动）\n'
    '\tvar 掌教标题 := Button.new()\n'
    '\t掌教标题.text = "《太玄宗门录》· 掌教治宗"\n'
    '\t掌教标题.flat = true\n'
    '\t掌教标题.add_theme_font_size_override("font_size", FONT_PANEL_B)\n'
    '\t掌教标题.add_theme_color_override("font_color", 暗金)\n'
    '\t掌教标题.pressed.connect(_on_掌教点击彩蛋)\n'
    '\t顶栏.add_child(掌教标题)\n'
    '\tvar 别名 := Label.new()\n'
    '\t别名.text = "又名：开局接手太玄宗"\n'
    '\t别名.add_theme_font_size_override("font_size", FONT_AUX)\n'
    '\t别名.add_theme_color_override("font_color", 宣纸亮)\n'
    '\t顶栏.add_child(别名)\n'
    '\t状态栏 = Label.new()\n'
    '\t状态栏.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART\n'
    '\t状态栏.mouse_filter = Control.MOUSE_FILTER_IGNORE   # 让点击穿透到状态面板，供入门指引步骤①Hook\n'
    '\tvar 状态面板: PanelContainer = 新面板("")\n'
    '\t状态面板.get_child(0).add_child(状态栏)\n'
    '\t状态面板.add_theme_stylebox_override("panel", _暗墨面板())\n'
    '\t状态栏.add_theme_color_override("font_color", 暗金)\n'
    '\t顶栏.add_child(状态面板)\n'
    '\t入门指引_状态面板 = 状态面板\n'
    '\n'
    '\t# 顶栏角落图标：设置（存读/新游戏，常驻）+ 调试（推演中心，Debug 可见）\n'
    '\tvar 顶栏角 := HBoxContainer.new()\n'
    '\t顶栏角.alignment = BoxContainer.ALIGN_END\n'
    '\t顶栏角.add_theme_constant_override("separation", 6)\n'
    '\t顶栏.add_child(顶栏角)\n'
    '\t设置图标 = Button.new(); 设置图标.text = "⚙"\n'
    '\t设置图标.tooltip_text = "设置（存读 / 新游戏）"\n'
    '\t设置图标.pressed.connect(_弹_设置)\n'
    '\t顶栏角.add_child(设置图标)\n'
    '\tif OS.is_debug_build():\n'
    '\t\t调试图标 = Button.new(); 调试图标.text = "🐞"\n'
    '\t\t调试图标.tooltip_text = "推演中心（调试）"\n'
    '\t\t调试图标.pressed.connect(_弹_推演中心)\n'
    '\t\t顶栏角.add_child(调试图标)\n'
    '\t\t入门指引_推演按钮 = 调试图标\n'
    '\n'
    '\t# 离山汇总（离线收益简报）：建为独立弹窗，不内联首页（§1.2 B3）\n'
    '\t离山面板 = 新面板("✦ 离山汇总（你离开期间）")\n'
    '\tvar 离山根 := VBoxContainer.new()\n'
    '\t离山面板.add_child(离山根)\n'
    '\t离山内容区 = VBoxContainer.new()\n'
    '\t离山根.add_child(离山内容区)\n'
    '\t离山面板.custom_minimum_size = Vector2(0, 140)\n'
    '\t离山面板.gui_input.connect(_on_离山面板_点击)\n'
    '\tvar 离山关 := Button.new(); 离山关.text = "归藏"; 离山关.custom_minimum_size = Vector2(0, 44)\n'
    '\t离山关.pressed.connect(_关_离山简报)\n'
    '\t离山根.add_child(离山关)\n'
    '\t# 战报 Label 保留作兼容降级显示（旧存档/无结构化数据时用）\n'
    '\t战报 = Label.new()\n'
    '\t战报.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART\n'
    '\t战报.visible = false   # 默认隐藏，新UI优先\n',
    1,
))

# 6) tb TabBar -> 5 Tab + _on_主导航切换
reps.append((
    '\t# 标签页（固定底部，不再被内容推走）\n'
    '\tvar tb := TabBar.new()\n'
    '\tfor n in 页名:\n'
    '\t\ttb.add_tab(n)\n'
    '\t\ttb.tab_changed.connect(_on_切页)\n'
    '\t底部区.add_child(tb)\n'
    '\t标签栏 = tb\n',
    '\t# 底部主导航：复用 标签栏(TabBar)，5 核心 Tab 常驻、跨页不释放（§1.4）\n'
    '\tvar tb := TabBar.new()\n'
    '\tfor n in 页名:\n'
    '\t\ttb.add_tab(n)\n'
    '\ttb.tab_changed.connect(_on_主导航切换)\n'
    '\t底部区.add_child(tb)\n'
    '\t标签栏 = tb\n',
    1,
))

# 7) 滚动 + 页控 -> 持久 VBox + _建_弟子页头()
reps.append((
    '\t# 滚动内容区（三页仅一页可见；硬编码最小高度防嵌套ScrollContainer高度坍塌）\n'
    '\tvar 滚动 := ScrollContainer.new()\n'
    '\t滚动.size_flags_horizontal = Control.SIZE_EXPAND_FILL\n'
    '\t滚动.size_flags_vertical = Control.SIZE_EXPAND_FILL\n'
    '\t滚动.custom_minimum_size = Vector2(0, 360)\n'
    '\t中区内容.add_child(滚动)\n'
    '\t列表 = VBoxContainer.new(); 列表.add_theme_constant_override("separation", 6); 列表.size_flags_horizontal = Control.SIZE_EXPAND_FILL; 列表.size_flags_vertical = Control.SIZE_EXPAND_FILL\n'
    '\t抉择区 = VBoxContainer.new(); 抉择区.add_theme_constant_override("separation", 6); 抉择区.size_flags_horizontal = Control.SIZE_EXPAND_FILL; 抉择区.size_flags_vertical = Control.SIZE_EXPAND_FILL\n'
    '\t御兽区 = VBoxContainer.new(); 御兽区.add_theme_constant_override("separation", 4); 御兽区.size_flags_horizontal = Control.SIZE_EXPAND_FILL; 御兽区.size_flags_vertical = Control.SIZE_EXPAND_FILL\n'
    '\t纪事区 = VBoxContainer.new(); 纪事区.add_theme_constant_override("separation", 4); 纪事区.size_flags_horizontal = Control.SIZE_EXPAND_FILL; 纪事区.size_flags_vertical = Control.SIZE_EXPAND_FILL\n'
    '\t滚动.add_child(列表); 滚动.add_child(抉择区); 滚动.add_child(御兽区); 滚动.add_child(纪事区)\n'
    '\t抉择区.visible = false; 御兽区.visible = false; 纪事区.visible = false\n'
    '\t页控 = {"弟子": 列表, "待抉择": 抉择区, "御兽": 御兽区, "纪事": 纪事区}\n',
    '\t# 持久内容 VBox（跨页不销毁，仅随整页切换重挂载/卸载；刷新逻辑直接复用）\n'
    '\t列表 = VBoxContainer.new(); 列表.add_theme_constant_override("separation", 6); 列表.size_flags_horizontal = Control.SIZE_EXPAND_FILL; 列表.size_flags_vertical = Control.SIZE_EXPAND_FILL\n'
    '\t抉择区 = VBoxContainer.new(); 抉择区.add_theme_constant_override("separation", 6); 抉择区.size_flags_horizontal = Control.SIZE_EXPAND_FILL; 抉择区.size_flags_vertical = Control.SIZE_EXPAND_FILL\n'
    '\t御兽区 = VBoxContainer.new(); 御兽区.add_theme_constant_override("separation", 4); 御兽区.size_flags_horizontal = Control.SIZE_EXPAND_FILL; 御兽区.size_flags_vertical = Control.SIZE_EXPAND_FILL\n'
    '\t纪事区 = VBoxContainer.new(); 纪事区.add_theme_constant_override("separation", 4); 纪事区.size_flags_horizontal = Control.SIZE_EXPAND_FILL; 纪事区.size_flags_vertical = Control.SIZE_EXPAND_FILL\n'
    '\t# 弟子页头（总战力+排序+提示）持久，跨切换保留\n'
    '\t_建_弟子页头()\n',
    1,
))

# 8) 弟子页头内建块 -> 移除（由 _建_弟子页头 处理）
reps.append((
    '\t# P0：弟子总览页头（宗门总战力 + 排序按钮），置于滚动区上方、仅弟子页可见\n'
    '\t弟子页头 = VBoxContainer.new()\n'
    '\t弟子页头.add_theme_constant_override("separation", 4)\n'
    '\tvar 战力行 := HBoxContainer.new()\n'
    '\t总战力标签 = Label.new()\n'
    '\t总战力标签.text = "宗门总战力：0"\n'
    '\t总战力标签.add_theme_font_size_override("font_size", FONT_SUB)\n'
    '\t总战力标签.add_theme_color_override("font_color", 暗金)\n'
    '\t战力行.add_child(总战力标签)\n'
    '\t弟子页头.add_child(战力行)\n'
    '\tvar 排序行 := HBoxContainer.new()\n'
    '\t排序行.add_theme_constant_override("separation", 6)\n'
    '\tfor 名 in ["默认", "战力", "境界", "资质"]:\n'
    '\t\tvar 钮 := Button.new(); 钮.text = 名\n'
    '\t\t钮.add_theme_font_size_override("font_size", FONT_AUX)\n'
    '\t\t钮.pressed.connect(_on_排序.bind(名))\n'
    '\t\t排序按钮组[名] = 钮\n'
    '\t\t排序行.add_child(钮)\n'
    '\t弟子页头.add_child(排序行)\n'
    '\t中区内容.add_child(弟子页头)\n'
    '\t中区内容.move_child(弟子页头, 中区内容.get_children().find(滚动))\n'
    '\t弟子页头.visible = true\n'
    '\t_刷新排序按钮()\n'
    '\t# 招徒后高亮弟子入口的淡提示（仅 FTUE 步④期间显示）\n'
    '\t入门指引_弟子提示 = Label.new()\n'
    '\t入门指引_弟子提示.text = "可前往「弟子」页查看详情 →"\n'
    '\t入门指引_弟子提示.add_theme_font_size_override("font_size", FONT_AUX)\n'
    '\t入门指引_弟子提示.add_theme_color_override("font_color", 暗金)\n'
    '\t入门指引_弟子提示.visible = false\n'
    '\t弟子页头.add_child(入门指引_弟子提示)\n',
    '\t# 弟子页头由 _建_弟子页头() 持久构建（见下方整页切换区块）\n',
    1,
))

# 10) 末尾：构建默认首页
reps.append((
    '\tGame.弟子变动.connect(刷新)\n'
    '\tGame.战报更新.connect(_on_战报)\n'
    '\tGame.奇遇发生.connect(_on_奇遇发生)   # Step 2：奇遇三场景触发后展示调度\n'
    '\t# 入门指引步骤①④的点击 Hook：点状态栏→资源；点离山面板→考评\n'
    '\t入门指引_状态面板.gui_input.connect(_on_状态面板_点击)\n'
    '\t离山面板.gui_input.connect(_on_离山面板_点击)\n'
    '\n'
    '\t# 标题屏拦截：自动推演延后到标题屏关闭（点或继续）之后，避免新档一开机空推一天\n'
    '\t_显示标题()\n',
    '\tGame.弟子变动.connect(刷新)\n'
    '\tGame.战报更新.connect(_on_战报)\n'
    '\tGame.奇遇发生.connect(_on_奇遇发生)   # Step 2：奇遇三场景触发后展示调度\n'
    '\t# 入门指引步骤①的点击 Hook：点状态栏→资源（离山面板 Hook 在离山面板创建处绑定）\n'
    '\t入门指引_状态面板.gui_input.connect(_on_状态面板_点击)\n'
    '\n'
    '\t# 构建默认首页（宗门），整页切换机制启动\n'
    '\t_on_主导航切换(0)\n'
    '\n'
    '\t# 标题屏拦截：自动推演延后到标题屏关闭（点或继续）之后，避免新档一开机空推一天\n'
    '\t_显示标题()\n',
    1,
))

# 11) _on_切页 -> 生命周期 + 五大核心页 + 二级页调度 + 新辅助函数
BIG = (
    'func _on_主导航切换(i: int):\n'
    '\tvar 名: String = 页名[i]\n'
    '\t_二级页 = ""\n'
    '\t_卸下当前页()\n'
    '\tmatch 名:\n'
    '\t\t"宗门": _建_宗门页()\n'
    '\t\t"弟子": _建_弟子页()\n'
    '\t\t"御兽": _建_御兽页()\n'
    '\t\t"历练": _建_历练页()\n'
    '\t\t"纪事": _建_纪事页()\n'
    '\t当前页名 = 名\n'
    '\tif 名 == "弟子" and Game.引导阶段 == 4:\n'
    '\t\t_自动展开首弟子()   # 首进弟子页自动展开首名弟子详情（不自动完成步④）\n'
    '\n'
    'func _卸下当前页():\n'
    '\tif 当前页容器 == null:\n'
    '\t\treturn\n'
    '\tfor n in 当前页持久节点:\n'
    '\t\tif is_instance_valid(n) and n.get_parent() != null:\n'
    '\t\t\tn.get_parent().remove_child(n)\n'
    '\t当前页容器.queue_free()\n'
    '\t当前页容器 = null\n'
    '\t当前页持久节点.clear()\n'
    '\n'
    'func _新页容器() -> ScrollContainer:\n'
    '\tvar 页 := ScrollContainer.new()\n'
    '\t页.size_flags_horizontal = Control.SIZE_EXPAND_FILL\n'
    '\t页.size_flags_vertical = Control.SIZE_EXPAND_FILL\n'
    '\t页.custom_minimum_size = Vector2(0, 680)\n'
    '\tvar 内容 := VBoxContainer.new()\n'
    '\t内容.size_flags_horizontal = Control.SIZE_EXPAND_FILL\n'
    '\t内容.size_flags_vertical = Control.SIZE_EXPAND_FILL\n'
    '\t内容.add_theme_constant_override("separation", 6)\n'
    '\t页.add_child(内容)\n'
    '\t内容区.add_child(页)\n'
    '\t当前页容器 = 页\n'
    '\treturn 页\n'
    '\n'
    'func _建_宗门页():\n'
    '\tvar 页 := _新页容器()\n'
    '\tvar 内容: Control = 页.get_child(0)\n'
    '\t# W3 宗门全景概要（简洁卡片，非明细列表）\n'
    '\t内容.add_child(_宗门全景卡())\n'
    '\t# W4 快捷入口网格（受控，禁止滚动按钮墙）\n'
    '\tvar 网格 := GridContainer.new()\n'
    '\t网格.columns = 3\n'
    '\t网格.add_theme_constant_override("h_separation", 8)\n'
    '\t网格.add_theme_constant_override("v_separation", 8)\n'
    '\t内容.add_child(网格)\n'
    '\t_宗门网格入口.clear()\n'
    '\tvar 入口 := ["洞府", "修炼", "殿阁", "坊市", "差事", "库藏"]\n'
    '\tfor 名 in 入口:\n'
    '\t\tvar 钮 := Button.new()\n'
    '\t\t钮.text = 名\n'
    '\t\t钮.custom_minimum_size = Vector2(0, 56)\n'
    '\t\t钮.pressed.connect(_进_二级页.bind(名))\n'
    '\t\t网格.add_child(钮)\n'
    '\t\t_宗门网格入口[名] = 钮\n'
    '\t# 灰锁（坊市/差事 受锁：disabled+🔒+tooltip，点击不跳转）\n'
    '\t入门指引_坊市按钮 = _宗门网格入口.get("坊市", null)\n'
    '\t入门指引_差事按钮 = _宗门网格入口.get("差事", null)\n'
    '\t_刷新功能解锁()\n'
    '\t当前页持久节点 = []\n'
    '\n'
    'func _宗门全景卡() -> PanelContainer:\n'
    '\tvar 卡: PanelContainer = 新面板("—— 宗门全景 ——")\n'
    '\t卡.add_theme_stylebox_override("panel", _暗墨面板())\n'
    '\tvar 文 := VBoxContainer.new()\n'
    '\t卡.add_child(文)\n'
    '\tvar 行 := Label.new()\n'
    '\t行.text = "门派 Lv%d · 声望 %d · 繁荣 %d" % [Game.门派等级, Game.声望, Game.繁荣]\n'
    '\t行.add_theme_color_override("font_color", 暗金)\n'
    '\t文.add_child(行)\n'
    '\tvar 行二 := Label.new()\n'
    '\t行二.text = "灵石 %d｜灵草 %d｜矿石 %d｜灵气 %d｜贡献 %d" % [Game.灵石, Game.灵草, Game.矿石, Game.灵气, Game.贡献点]\n'
    '\t行二.add_theme_color_override("font_color", 次墨)\n'
    '\t文.add_child(行二)\n'
    '\tvar 行三 := Label.new()\n'
    '\t行三.text = "弟子 %d 人｜气力 %d/%d｜%s" % [Game.弟子列表.size(), Game.体力, Game.体力上限(), Game.时间文本()]\n'
    '\t行三.add_theme_color_override("font_color", 次墨)\n'
    '\t文.add_child(行三)\n'
    '\treturn 卡\n'
    '\n'
    'func _建_弟子页():\n'
    '\tvar 页 := _新页容器()\n'
    '\tvar 内容: Control = 页.get_child(0)\n'
    '\t内容.add_child(弟子页头)   # 持久：总战力 + 排序 + 提示\n'
    '\t# 二级 Tab：名录 / 接引（待抉择并入接引）\n'
    '\tvar 二级 := TabBar.new()\n'
    '\t二级.add_tab("名录"); 二级.add_tab("接引")\n'
    '\t二级.tab_changed.connect(_on_弟子二级切换)\n'
    '\t内容.add_child(二级)\n'
    '\t# 名录\n'
    '\t内容.add_child(列表)\n'
    '\t# 接引（待抉择 + 招收）\n'
    '\tvar 接引框 := VBoxContainer.new()\n'
    '\t接引框.size_flags_horizontal = Control.SIZE_EXPAND_FILL\n'
    '\t接引框.add_theme_constant_override("separation", 6)\n'
    '\t接引框.add_child(抉择区)\n'
    '\tvar 招 := Button.new(); 招.text = "开启接引大典"; 招.custom_minimum_size = Vector2(0, 44)\n'
    '\t招.pressed.connect(_on_测灵根)\n'
    '\t接引框.add_child(招)\n'
    '\t入门指引_招收按钮 = 招\n'
    '\t内容.add_child(接引框)\n'
    '\t# 应用二级 Tab 选中态（跨切换保留）\n'
    '\t二级.current_tab = _弟子二级tab\n'
    '\t_应用_弟子二级tab()\n'
    '\t当前页持久节点 = [弟子页头, 列表, 抉择区]\n'
    '\n'
    'func _on_弟子二级切换(i: int):\n'
    '\t_弟子二级tab = i\n'
    '\t_应用_弟子二级tab()\n'
    '\n'
    'func _应用_弟子二级tab():\n'
    '\tvar 名录: bool = (_弟子二级tab == 0)\n'
    '\t列表.visible = 名录\n'
    '\tvar 接引框 := 抉择区.get_parent()\n'
    '\tif 接引框 != null:\n'
    '\t\t接引框.visible = not 名录\n'
    '\n'
    'func _建_御兽页():\n'
    '\tvar 页 := _新页容器()\n'
    '\tvar 内容: Control = 页.get_child(0)\n'
    '\tvar 快进 := Button.new(); 快进.text = "御兽快进（孵化30日）"; 快进.custom_minimum_size = Vector2(0, 44)\n'
    '\t快进.pressed.connect(_on_快进)\n'
    '\t内容.add_child(快进)\n'
    '\t内容.add_child(御兽区)   # 持久\n'
    '\t当前页持久节点 = [御兽区]\n'
    '\n'
    'func _建_历练页():\n'
    '\tvar 页 := _新页容器()\n'
    '\tvar 内容: Control = 页.get_child(0)\n'
    '\tvar 头 := Label.new()\n'
    '\t头.text = "⚔ 历练征途"\n'
    '\t头.add_theme_font_size_override("font_size", FONT_PANEL_B)\n'
    '\t头.add_theme_color_override("font_color", 暗金)\n'
    '\t内容.add_child(头)\n'
    '\t内容.add_child(_玄玉占位按钮())\n'
    '\tvar 体力标 := Label.new()\n'
    '\t体力标.text = "气力：%d / %d" % [Game.体力, Game.体力上限()]\n'
    '\t体力标.add_theme_color_override("font_color", 次墨)\n'
    '\t内容.add_child(体力标)\n'
    '\tvar 滚动 := ScrollContainer.new()\n'
    '\t滚动.size_flags_vertical = Control.SIZE_EXPAND_FILL\n'
    '\t滚动.size_flags_horizontal = Control.SIZE_EXPAND_FILL\n'
    '\t内容.add_child(滚动)\n'
    '\tvar 列 := VBoxContainer.new()\n'
    '\t列.add_theme_constant_override("separation", 4)\n'
    '\t滚动.add_child(列)\n'
    '\t历练滚动列 = 列   # 持久引用，战斗胜利后刷新用\n'
    '\tvar 章名: Dictionary = {1: "第一章·后山秘境", 2: "第二章·青冥古道", 3: "第三章·玄雾峡谷"}\n'
    '\tfor 章 in [1, 2, 3]:\n'
    '\t\tvar 章标 := Label.new()\n'
    '\t\t章标.text = "【%s】" % 章名[章]\n'
    '\t\t章标.add_theme_color_override("font_color", 青灰)\n'
    '\t\t列.add_child(章标)\n'
    '\t\tfor s in StageDataLoader.get_all_stages():\n'
    '\t\t\tif int(s.get("chapter", "0")) != 章:\n'
    '\t\t\t\tcontinue\n'
    '\t\t\t列.add_child(_历练秘境卡(s))\n'
    '\t当前页持久节点 = []\n'
    '\n'
    'func _建_纪事页():\n'
    '\tvar 页 := _新页容器()\n'
    '\tvar 内容: Control = 页.get_child(0)\n'
    '\t内容.add_child(纪事区)   # 持久（刷新纪事在其内建分类 Tab）\n'
    '\t刷新纪事()\n'
    '\t当前页持久节点 = [纪事区]\n'
    '\n'
    'func _进_二级页(名: String):\n'
    '\t_二级页 = 名\n'
    '\t_建_二级页(名)\n'
    '\n'
    'func _建_二级页(名: String):\n'
    '\t_卸下当前页()\n'
    '\tvar 页 := _新页容器()\n'
    '\tvar 内容: Control = 页.get_child(0)\n'
    '\tvar 返回 := Button.new(); 返回.text = "← 返回宗门"; 返回.custom_minimum_size = Vector2(0, 44)\n'
    '\t返回.pressed.connect(_返回宗门)\n'
    '\t内容.add_child(返回)\n'
    '\tmatch 名:\n'
    '\t\t"坊市": _填_坊市页(内容)\n'
    '\t\t"差事": _填_差事页(内容)\n'
    '\t\t"殿阁": _填_殿阁页(内容)\n'
    '\t\t"库藏": _填_库藏页(内容)\n'
    '\t\t"洞府": _填_洞府页(内容)\n'
    '\t\t"修炼": _填_修炼页(内容)\n'
    '\t当前页名 = "宗门"   # 主导航仍高亮宗门\n'
    '\t当前页持久节点 = []\n'
    '\n'
    'func _返回宗门():\n'
    '\t_on_主导航切换(0)\n'
    '\n'
    'func _建_弟子页头():\n'
    '\t弟子页头 = VBoxContainer.new()\n'
    '\t弟子页头.add_theme_constant_override("separation", 4)\n'
    '\tvar 战力行 := HBoxContainer.new()\n'
    '\t总战力标签 = Label.new()\n'
    '\t总战力标签.text = "宗门总战力：0"\n'
    '\t总战力标签.add_theme_font_size_override("font_size", FONT_SUB)\n'
    '\t总战力标签.add_theme_color_override("font_color", 暗金)\n'
    '\t战力行.add_child(总战力标签)\n'
    '\t弟子页头.add_child(战力行)\n'
    '\tvar 排序行 := HBoxContainer.new()\n'
    '\t排序行.add_theme_constant_override("separation", 6)\n'
    '\tfor 名 in ["默认", "战力", "境界", "资质"]:\n'
    '\t\tvar 钮 := Button.new(); 钮.text = 名\n'
    '\t\t钮.add_theme_font_size_override("font_size", FONT_AUX)\n'
    '\t\t钮.pressed.connect(_on_排序.bind(名))\n'
    '\t\t排序按钮组[名] = 钮\n'
    '\t\t排序行.add_child(钮)\n'
    '\t弟子页头.add_child(排序行)\n'
    '\t_刷新排序按钮()\n'
    '\t入门指引_弟子提示 = Label.new()\n'
    '\t入门指引_弟子提示.text = "可前往「弟子」页查看详情 →"\n'
    '\t入门指引_弟子提示.add_theme_font_size_override("font_size", FONT_AUX)\n'
    '\t入门指引_弟子提示.add_theme_color_override("font_color", 暗金)\n'
    '\t入门指引_弟子提示.visible = false\n'
    '\t弟子页头.add_child(入门指引_弟子提示)\n'
    '\n'
    'func _弹_设置():\n'
    '\tvar 遮 := ColorRect.new()\n'
    '\t遮.color = 弹窗遮罩\n'
    '\t遮.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)\n'
    '\t遮.mouse_filter = Control.MOUSE_FILTER_STOP\n'
    '\t遮.name = "设置弹窗"\n'
    '\tadd_child(遮)\n'
    '\tvar pc: PanelContainer = 新面板("⚙ 设置")\n'
    '\tpc.anchor_left = 0.5; pc.anchor_top = 0.5; pc.anchor_right = 0.5; pc.anchor_bottom = 0.5\n'
    '\tpc.offset_left = -160; pc.offset_top = -120; pc.offset_right = 160; pc.offset_bottom = 120\n'
    '\t遮.add_child(pc)\n'
    '\tvar 内容: Control = pc.get_child(0)\n'
    '\tvar 存 := Button.new(); 存.text = "存档"; 存.custom_minimum_size = Vector2(0, 44); 存.pressed.connect(_on_存档); 内容.add_child(存)\n'
    '\tvar 读 := Button.new(); 读.text = "读档"; 读.custom_minimum_size = Vector2(0, 44); 读.pressed.connect(_on_读档); 内容.add_child(读)\n'
    '\tvar 新 := Button.new(); 新.text = "新游戏"; 新.custom_minimum_size = Vector2(0, 44); 新.pressed.connect(_on_新游戏); 内容.add_child(新)\n'
    '\tvar 关 := Button.new(); 关.text = "关闭"; 关.custom_minimum_size = Vector2(0, 44); 关.pressed.connect(func(): 遮.queue_free()); 内容.add_child(关)\n'
    '\n'
    'func _弹_推演中心():\n'
    '\tvar 遮 := ColorRect.new()\n'
    '\t遮.color = 弹窗遮罩\n'
    '\t遮.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)\n'
    '\t遮.mouse_filter = Control.MOUSE_FILTER_STOP\n'
    '\t遮.name = "推演中心"\n'
    '\tadd_child(遮)\n'
    '\tvar pc: PanelContainer = 新面板("🐞 推演中心（调试）")\n'
    '\tpc.anchor_left = 0.5; pc.anchor_top = 0.5; pc.anchor_right = 0.5; pc.anchor_bottom = 0.5\n'
    '\tpc.offset_left = -170; pc.offset_top = -200; pc.offset_right = 170; pc.offset_bottom = 200\n'
    '\t遮.add_child(pc)\n'
    '\tvar 内容: Control = pc.get_child(0)\n'
    '\tvar 推演 := Button.new(); 推演.text = "推演汇总"; 推演.custom_minimum_size = Vector2(0, 44); 推演.pressed.connect(_on_推演); 内容.add_child(推演)\n'
    '\tvar 推演7 := Button.new(); 推演7.text = "推演7天"; 推演7.custom_minimum_size = Vector2(0, 44); 推演7.pressed.connect(_on_推演七日); 内容.add_child(推演7)\n'
    '\tvar 快进年 := Button.new(); 快进年.text = "推演1年"; 快进年.custom_minimum_size = Vector2(0, 44); 快进年.pressed.connect(_on_推荐一年); 内容.add_child(快进年)\n'
    '\tvar 调试 := Button.new(); 调试.text = "调试战斗"; 调试.custom_minimum_size = Vector2(0, 44); 调试.pressed.connect(_on_调试战斗); 内容.add_child(调试)\n'
    '\tif OS.is_debug_build():\n'
    '\t\tvar 强制征伐 := Button.new(); 强制征伐.text = "强制征伐"; 强制征伐.custom_minimum_size = Vector2(0, 44); 强制征伐.pressed.connect(_on_强制征伐); 内容.add_child(强制征伐)\n'
    '\t\tvar 重置 := Button.new(); 重置.text = "重置入门指引"; 重置.custom_minimum_size = Vector2(0, 44); 重置.pressed.connect(_on_重置入门指引); 内容.add_child(重置)\n'
    '\t\tvar 天品 := Button.new(); 天品.text = "强制天品"; 天品.custom_minimum_size = Vector2(0, 44); 天品.pressed.connect(_on_强制天品); 内容.add_child(天品)\n'
    '\t\tvar 聚气 := Button.new(); 聚气.text = "强制聚气丹"; 聚气.custom_minimum_size = Vector2(0, 44); 聚气.pressed.connect(_on_强制聚气丹); 内容.add_child(聚气)\n'
    '\tvar 关 := Button.new(); 关.text = "关闭"; 关.custom_minimum_size = Vector2(0, 44); 关.pressed.connect(func(): 遮.queue_free()); 内容.add_child(关)\n'
    '\n'
    'func _弹_离山简报():\n'
    '\tif 离山面板 == null or not is_instance_valid(离山面板):\n'
    '\t\treturn\n'
    '\tif 离山内容区.get_child_count() == 0:\n'
    '\t\treturn\n'
    '\tif get_node_or_null("离山简报遮") != null:\n'
    '\t\treturn   # 已开\n'
    '\tvar 遮 := ColorRect.new()\n'
    '\t遮.name = "离山简报遮"\n'
    '\t遮.color = 弹窗遮罩\n'
    '\t遮.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)\n'
    '\t遮.mouse_filter = Control.MOUSE_FILTER_STOP\n'
    '\tadd_child(遮)\n'
    '\tvar 框 := PanelContainer.new()\n'
    '\t框.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)\n'
    '\t框.offset_left = 20; 框.offset_right = -20; 框.offset_top = 60; 框.offset_bottom = -20\n'
    '\t遮.add_child(框)\n'
    '\t框.add_child(离山面板)   # 重挂：离山面板 成为 框 子节点\n'
    '\n'
    'func _关_离山简报():\n'
    '\tif 离山面板 != null and 离山面板.get_parent() != null:\n'
    '\t\t离山面板.get_parent().remove_child(离山面板)\n'
    '\tvar 遮 := get_node_or_null("离山简报遮")\n'
    '\tif 遮 != null:\n'
    '\t\t遮.queue_free()\n'
    '\n'
    'func _填_洞府页(内容: Control):\n'
    '\tvar 头 := Label.new(); 头.text = "⛰ 洞府经营总览"; 头.add_theme_font_size_override("font_size", FONT_PANEL_B); 头.add_theme_color_override("font_color", 暗金); 内容.add_child(头)\n'
    '\tif Game.司职列表.is_empty():\n'
    '\t\tvar 空 := Label.new(); 空.text = "（尚无司职，招徒后自动建置）"; 内容.add_child(空)\n'
    '\t\treturn\n'
    '\tfor key in Game.司职列表.keys():\n'
    '\t\tvar 堂: Dictionary = Game.司职列表[key]\n'
    '\t\tvar 名: String = 堂.get("名称", key)\n'
    '\t\tvar 成员数: int = (堂.get("成员", []) as Array).size()\n'
    '\t\tvar 产: int = Game.预估殿阁产出(key)\n'
    '\t\tvar 卡 := 新面板(名)\n'
    '\t\t卡.add_theme_stylebox_override("panel", _暗墨面板())\n'
    '\t\tvar 文 := VBoxContainer.new(); 卡.add_child(文)\n'
    '\t\tvar l1 := Label.new(); l1.text = "成员 %d 人｜预估月产 +%d 灵石" % [成员数, 产]; l1.add_theme_color_override("font_color", 次墨); 文.add_child(l1)\n'
    '\t\t内容.add_child(卡)\n'
    '\n'
    'func _填_修炼页(内容: Control):\n'
    '\tvar 头 := Label.new(); 头.text = "🧘 修炼设施"; 头.add_theme_font_size_override("font_size", FONT_PANEL_B); 头.add_theme_color_override("font_color", 暗金); 内容.add_child(头)\n'
    '\tif Game.弟子列表.is_empty():\n'
    '\t\tvar 空 := Label.new(); 空.text = "（尚无弟子，先去「弟子」页接引）"; 内容.add_child(空)\n'
    '\t\treturn\n'
    '\tfor d in Game.弟子列表:\n'
    '\t\tvar 卡 := 新面板(d.姓名)\n'
    '\t\t卡.add_theme_stylebox_override("panel", _暗墨面板())\n'
    '\t\tvar 文 := VBoxContainer.new(); 卡.add_child(文)\n'
    '\t\tvar l1 := Label.new(); l1.text = "境界：%s" % d.境界; l1.add_theme_color_override("font_color", 次墨); 文.add_child(l1)\n'
    '\t\tvar 进: int = int(d.修炼进度 * 100)\n'
    '\t\tvar l2 := Label.new(); l2.text = "修炼进度：%d%%" % 进; l2.add_theme_color_override("font_color", 次墨); 文.add_child(l2)\n'
    '\t\tif d.突破冷却剩余 > 0:\n'
    '\t\t\tvar l3 := Label.new(); l3.text = "突破冷却：%d 日" % int(d.突破冷却剩余); l3.add_theme_color_override("font_color", 朱砂); 文.add_child(l3)\n'
    '\t\t内容.add_child(卡)\n'
    '\n'
    'func _填_库藏页(内容: Control):\n'
    '\tvar 头 := Label.new(); 头.text = "📒 宗门库藏"; 头.add_theme_font_size_override("font_size", FONT_PANEL_B); 头.add_theme_color_override("font_color", 暗金); 内容.add_child(头)\n'
    '\tvar 总产: int = Game.预估月产出()\n'
    '\tvar 概 := Label.new(); 概.text = "预估月产出：+%d 灵石（含弟子修炼 %d）" % [总产, Game.弟子列表.size() * 2]; 概.add_theme_color_override("font_color", 暗金); 内容.add_child(概)\n'
    '\tvar 资 := Label.new(); 资.text = "现储：灵石 %d｜灵草 %d｜矿石 %d｜灵气 %d｜贡献 %d" % [Game.灵石, Game.灵草, Game.矿石, Game.灵气, Game.贡献点]; 资.add_theme_color_override("font_color", 次墨); 内容.add_child(资)\n'
    '\t内容.add_child(小标题("—— 各司职产出 ——", 15))\n'
    '\tfor key in Game.司职列表.keys():\n'
    '\t\tvar 堂: Dictionary = Game.司职列表[key]\n'
    '\t\tvar 名: String = 堂.get("名称", key)\n'
    '\t\tvar 产: int = Game.预估殿阁产出(key)\n'
    '\t\tvar l := Label.new(); l.text = "%s：+%d /月" % [名, 产]; l.add_theme_color_override("font_color", 次墨); 内容.add_child(l)\n'
)
reps.append((
    'func _on_切页(i: int):\n'
    '\tvar 名: String = 页名[i]\n'
    '\tfor k in 页控:\n'
    '\t\t页控[k].visible = (k == 名)\n'
    '\t弟子页头.visible = (名 == "弟子")   # P0：总战力+排序页头仅弟子页显示\n'
    '\tif 名 == "弟子" and Game.引导阶段 == 4:\n'
    '\t\t_自动展开首弟子()   # 首进弟子页自动展开首名弟子详情（不自动完成步④）\n',
    BIG,
    1,
))

# 应用
for idx, (old, new, n) in enumerate(reps):
    c = src.count(old)
    if c != n:
        sys.stderr.write("FAIL #%d: 期望 %d 次，实际 %d 次\n" % (idx, n, c))
        sys.stderr.write("---- 失败片段（前200字符）----\n")
        sys.stderr.write(old[:200] + "\n")
        sys.exit(1)
    src = src.replace(old, new)

with io.open(PATH, "w", encoding="utf-8", newline="") as f:
    f.write(src)
print("A1 OK: 全部 %d 处替换成功，已写回 main.gd" % len(reps))
