# -*- coding: utf-8 -*-
import io, sys

PATH = "E:/Xiuxian/taixuanzongmenlu/main.gd"
with io.open(PATH, "r", encoding="utf-8", newline="") as f:
    src = f.read()

reps = []

# === 类型注解修正（第10道门：var x := 函数调用 须显式类型）===
reps.append(('var 页 := _新页容器()', 'var 页: ScrollContainer = _新页容器()', 6))
reps.append(('var 入口 := ["洞府", "修炼", "殿阁", "坊市", "差事", "库藏"]',
             'var 入口: Array = ["洞府", "修炼", "殿阁", "坊市", "差事", "库藏"]', 1))
reps.append(('var 接引框 := 抉择区.get_parent()', 'var 接引框: Node = 抉择区.get_parent()', 1))
reps.append(('var 遮 := get_node_or_null("离山简报遮")', 'var 遮: Node = get_node_or_null("离山简报遮")', 1))
reps.append(('var 卡 := 新面板(', 'var 卡: PanelContainer = 新面板(', 2))

# === _on_坊市 -> 二级页 ===
reps.append((
    'func _on_坊市():\n'
    '\t_坊市面板()\n',
    'func _on_坊市():\n'
    '\t_建_二级页("坊市")\n',
    1,
))

# === _坊市面板 + _刷新坊市列表 -> _填_坊市页 + _刷新坊市列表(去掉弹窗遮罩)===
reps.append((
    'func _坊市面板():\n'
    '\tif Game.坊市上架集.is_empty():\n'
    '\t\tGame.刷新坊市上架()\n'
    '\tvar 遮 := ColorRect.new()\n'
    '\t遮.color = 弹窗遮罩\n'
    '\t遮.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)\n'
    '\t遮.mouse_filter = Control.MOUSE_FILTER_STOP\n'
    '\t遮.name = "坊市面板"\n'
    '\tadd_child(遮)\n'
    '\tvar pc: PanelContainer = 新面板("✦ 坊市（消耗灵石 · 周限购）")\n'
    '\t# 锚点居中：anchor 全 0.5 + offset 正负半宽高 = 精确居中，不受嵌套布局影响\n'
    '\tpc.anchor_left = 0.5; pc.anchor_top = 0.5; pc.anchor_right = 0.5; pc.anchor_bottom = 0.5\n'
    '\tpc.offset_left = -200; pc.offset_top = -260; pc.offset_right = 200; pc.offset_bottom = 260\n'
    '\t遮.add_child(pc)\n'
    '\tvar 内容: Control = pc.get_child(0)\n'
    '\tvar 结果 := Label.new(); 结果.text = _坊市提示; 内容.add_child(结果)\n'
    '\tvar 滚 := ScrollContainer.new(); 滚.custom_minimum_size = Vector2(380, 400); 内容.add_child(滚)\n'
    '\tvar 列 := VBoxContainer.new(); 滚.add_child(列)\n'
    '\t_刷新坊市列表(列, 结果, 遮)\n'
    '\t# 玄玉专区占位（S0 stub：置灰，敬请期待）\n'
    '\tvar 玄玉分隔 := HSeparator.new(); 玄玉分隔.modulate.a = 0.4; 内容.add_child(玄玉分隔)\n'
    '\tvar 玄玉标题 := Label.new(); 玄玉标题.text = "—— 玄玉专区（后续版本开放） ——"; 玄玉标题.modulate.a = 0.5; 内容.add_child(玄玉标题)\n'
    '\tfor r in Game._玄玉表():\n'
    '\t\tvar b := Button.new()\n'
    '\t\tb.text = "%s（%d 玄玉）" % [r.get("name", ""), int(r.get("price_xuanyu", "0"))]\n'
    '\t\tb.disabled = true\n'
    '\t\tb.tooltip_text = "付费功能，后续版本开放"\n'
    '\t\tb.mouse_filter = Control.MOUSE_FILTER_STOP\n'
    '\t\t内容.add_child(b)\n'
    '\n'
    'func _刷新坊市列表(列: VBoxContainer, 结果: Label, 遮: ColorRect):\n'
    '\tfor c in 列.get_children():\n'
    '\t\tc.queue_free()\n'
    '\tvar 等级名: String = Game.声望等级名[clamp(Game.声望, 0, Game.声望等级名.size() - 1)]\n'
    '\tfor r in Game._坊市表():\n'
    '\t\tif not (r.get("shop_id", "") in Game.坊市上架集):\n'
    '\t\t\tcontinue\n'
    '\t\tvar 名: String = r.get("item_name", "")\n'
    '\t\tvar 原价: int = int(r.get("price_lingjing", "0"))\n'
    '\t\tvar 折后: int = Game.坊市实价(原价)\n'
    '\t\tvar 折扣说明: String = "" if 折后 == 原价 else "（%s%d折）" % [等级名, int(Game.坊市折扣率() * 100)]\n'
    '\t\tvar 限: String = "日%d/周%d" % [int(r.get("limit_daily", "0")), int(r.get("limit_weekly", "0"))]\n'
    '\t\tvar 行 := HBoxContainer.new()\n'
    '\t\tvar 原价文本: String = "" if 折后 == 原价 else "原价%d " % 原价\n'
    '\t\tvar 标 := Label.new(); 标.text = "%s %s%d灵石 [%s]" % [名, 原价文本, 折后, 限]\n'
    '\t\tvar 买 := Button.new(); 买.text = "购买"\n'
    '\t\t买.pressed.connect(func():\n'
    '\t\t\tvar res: Dictionary = Game.购买坊市物品(r.get("shop_id", ""))\n'
    '\t\t\t结果.text = res.get("msg", "")\n'
    '\t\t\t_坊市提示 = res.get("msg", "")\n'
    '\t\t\t刷新()\n'
    '\t\t\t_刷新坊市列表(列, 结果, 遮)\n'
    '\t\t)\n'
    '\t\t行.add_child(标); 行.add_child(买)\n'
    '\t\t列.add_child(行)\n'
    '\t# —— 宗门库房分类展示（资源/装备/丹药/功法）——\n'
    '\tvar 库头 := Label.new(); 库头.text = "── 宗门库房（%d件）──" % Game.宗门库房.size(); 列.add_child(库头)\n'
    '\tvar 分组: Dictionary = {"资源": [], "装备": [], "丹药": [], "功法": []}\n'
    '\tfor it in Game.宗门库房:\n'
    '\t\tvar 类: String = it.类别\n'
    '\t\tif 类 == "法器":\n'
    '\t\t\t类 = "装备"\n'
    '\t\tif not 分组.has(类):\n'
    '\t\t\t分组[类] = []\n'
    '\t\t分组[类].append("%s·%s" % [it.名称, it.品阶])\n'
    '\tfor 类 in ["资源", "装备", "丹药", "功法"]:\n'
    '\t\tif 分组[类].size() > 0:\n'
    '\t\t\tvar 段 := HBoxContainer.new()\n'
    '\t\t\tvar 类标 := Label.new(); 类标.text = "[%s] " % 类; 段.add_child(类标)\n'
    '\t\t\tfor it in Game.宗门库房:\n'
    '\t\t\t\tvar 它类: String = "装备" if it.类别 == "法器" else it.类别\n'
    '\t\t\t\tif 它类 != 类:\n'
    '\t\t\t\t\tcontinue\n'
    '\t\t\t\tvar 钮 := Button.new(); 钮.text = "%s·%s" % [it.名称, it.品阶]\n'
    '\t\t\t\t钮.pressed.connect(_弹出物品详情.bind(it))\n'
    '\t\t\t\t段.add_child(钮)\n'
    '\t\t\t列.add_child(段)\n'
    '\tvar 关 := Button.new(); 关.text = "归藏"\n'
    '\t关.pressed.connect(func(): _坊市提示 = ""; 遮.queue_free())\n'
    '\t列.add_child(关)\n',
    'func _填_坊市页(内容: Control):\n'
    '\tif Game.坊市上架集.is_empty():\n'
    '\t\tGame.刷新坊市上架()\n'
    '\tvar 结果 := Label.new(); 结果.text = _坊市提示; 内容.add_child(结果)\n'
    '\tvar 滚 := ScrollContainer.new(); 滚.custom_minimum_size = Vector2(380, 400); 内容.add_child(滚)\n'
    '\tvar 列 := VBoxContainer.new(); 滚.add_child(列)\n'
    '\t_刷新坊市列表(列, 结果)\n'
    '\t# 玄玉专区占位（S0 stub：置灰，敬请期待）\n'
    '\tvar 玄玉分隔 := HSeparator.new(); 玄玉分隔.modulate.a = 0.4; 内容.add_child(玄玉分隔)\n'
    '\tvar 玄玉标题 := Label.new(); 玄玉标题.text = "—— 玄玉专区（后续版本开放） ——"; 玄玉标题.modulate.a = 0.5; 内容.add_child(玄玉标题)\n'
    '\tfor r in Game._玄玉表():\n'
    '\t\tvar b := Button.new()\n'
    '\t\tb.text = "%s（%d 玄玉）" % [r.get("name", ""), int(r.get("price_xuanyu", "0"))]\n'
    '\t\tb.disabled = true\n'
    '\t\tb.tooltip_text = "付费功能，后续版本开放"\n'
    '\t\tb.mouse_filter = Control.MOUSE_FILTER_STOP\n'
    '\t\t内容.add_child(b)\n'
    '\n'
    'func _刷新坊市列表(列: VBoxContainer, 结果: Label):\n'
    '\tfor c in 列.get_children():\n'
    '\t\tc.queue_free()\n'
    '\tvar 等级名: String = Game.声望等级名[clamp(Game.声望, 0, Game.声望等级名.size() - 1)]\n'
    '\tfor r in Game._坊市表():\n'
    '\t\tif not (r.get("shop_id", "") in Game.坊市上架集):\n'
    '\t\t\tcontinue\n'
    '\t\tvar 名: String = r.get("item_name", "")\n'
    '\t\tvar 原价: int = int(r.get("price_lingjing", "0"))\n'
    '\t\tvar 折后: int = Game.坊市实价(原价)\n'
    '\t\tvar 折扣说明: String = "" if 折后 == 原价 else "（%s%d折）" % [等级名, int(Game.坊市折扣率() * 100)]\n'
    '\t\tvar 限: String = "日%d/周%d" % [int(r.get("limit_daily", "0")), int(r.get("limit_weekly", "0"))]\n'
    '\t\tvar 行 := HBoxContainer.new()\n'
    '\t\tvar 原价文本: String = "" if 折后 == 原价 else "原价%d " % 原价\n'
    '\t\tvar 标 := Label.new(); 标.text = "%s %s%d灵石 [%s]" % [名, 原价文本, 折后, 限]\n'
    '\t\tvar 买 := Button.new(); 买.text = "购买"\n'
    '\t\t买.pressed.connect(func():\n'
    '\t\t\tvar res: Dictionary = Game.购买坊市物品(r.get("shop_id", ""))\n'
    '\t\t\t结果.text = res.get("msg", "")\n'
    '\t\t\t_坊市提示 = res.get("msg", "")\n'
    '\t\t\t刷新()\n'
    '\t\t\t_刷新坊市列表(列, 结果)\n'
    '\t\t)\n'
    '\t\t行.add_child(标); 行.add_child(买)\n'
    '\t\t列.add_child(行)\n'
    '\t# —— 宗门库房分类展示（资源/装备/丹药/功法）——\n'
    '\tvar 库头 := Label.new(); 库头.text = "── 宗门库房（%d件）──" % Game.宗门库房.size(); 列.add_child(库头)\n'
    '\tvar 分组: Dictionary = {"资源": [], "装备": [], "丹药": [], "功法": []}\n'
    '\tfor it in Game.宗门库房:\n'
    '\t\tvar 类: String = it.类别\n'
    '\t\tif 类 == "法器":\n'
    '\t\t\t类 = "装备"\n'
    '\t\tif not 分组.has(类):\n'
    '\t\t\t分组[类] = []\n'
    '\t\t分组[类].append("%s·%s" % [it.名称, it.品阶])\n'
    '\tfor 类 in ["资源", "装备", "丹药", "功法"]:\n'
    '\t\tif 分组[类].size() > 0:\n'
    '\t\t\tvar 段 := HBoxContainer.new()\n'
    '\t\t\tvar 类标 := Label.new(); 类标.text = "[%s] " % 类; 段.add_child(类标)\n'
    '\t\t\tfor it in Game.宗门库房:\n'
    '\t\t\t\tvar 它类: String = "装备" if it.类别 == "法器" else it.类别\n'
    '\t\t\t\tif 它类 != 类:\n'
    '\t\t\t\t\tcontinue\n'
    '\t\t\t\tvar 钮 := Button.new(); 钮.text = "%s·%s" % [it.名称, it.品阶]\n'
    '\t\t\t\t钮.pressed.connect(_弹出物品详情.bind(it))\n'
    '\t\t\t\t段.add_child(钮)\n'
    '\t\t\t列.add_child(段)\n',
    1,
))

# === _on_差事 + _差事面板 + _差事面板_重建 -> _建_二级页 + _填_差事页 + _刷新_差事页 ===
reps.append((
    'func _on_差事():\n'
    '\t_差事面板()\n'
    '\n'
    'func _差事面板():\n'
    '\tvar 遮 := ColorRect.new()\n'
    '\t遮.color = 弹窗遮罩\n'
    '\t遮.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)\n'
    '\t遮.mouse_filter = Control.MOUSE_FILTER_STOP\n'
    '\t遮.name = "差事面板"\n'
    '\tadd_child(遮)\n'
    '\tvar pc: PanelContainer = 新面板("✦ 差事中心")\n'
    '\tpc.anchor_left = 0.5; pc.anchor_top = 0.5; pc.anchor_right = 0.5; pc.anchor_bottom = 0.5\n'
    '\tpc.offset_left = -200; pc.offset_top = -260; pc.offset_right = 200; pc.offset_bottom = 260\n'
    '\t遮.add_child(pc)\n'
    '\tvar 内容: Control = pc.get_child(0)\n'
    '\tvar 结果 := Label.new(); 结果.text = _差事提示; 内容.add_child(结果)\n'
    '\tvar 滚 := ScrollContainer.new(); 滚.custom_minimum_size = Vector2(380, 400); 内容.add_child(滚)\n'
    '\tvar 列 := VBoxContainer.new(); 滚.add_child(列)\n'
    '\t# —— 日常差事 ——\n'
    '\tvar 日常倒计: int = max(0, (Game.上次日常日 + 1) - Game.累计游戏日)\n'
    '\tvar 日头 := Label.new(); 日头.text = "【日常】每日刷新(距%d日) 领灵石/灵气" % 日常倒计; 列.add_child(日头)\n'
    '\tfor i in Game.当前日常.size():\n'
    '\t\tvar q: Dictionary = Game.当前日常[i]\n'
    '\t\tvar 已领: bool = Game.日常已领[i] if i < Game.日常已领.size() else false\n'
    '\t\tvar 行 := HBoxContainer.new()\n'
    '\t\tvar 标 := Label.new()\n'
    '\t\t标.text = "%s：%s（石+%s 气+%s）%s" % [q.get("quest_name", ""), q.get("target_desc", ""), q.get("reward_lingjing", "0"), q.get("reward_lingqi", "0"), "✅" if 已领 else ""]\n'
    '\t\tvar 领 := Button.new(); 领.text = "领取" if not 已领 else "已领"\n'
    '\t\t领.disabled = 已领\n'
    '\t\t领.pressed.connect(func():\n'
    '\t\t\tvar res: Dictionary = Game.领取日常(i)\n'
    '\t\t\t_差事提示 = res.get("msg", "")\n'
    '\t\t\t_差事面板_重建(遮)\n'
    '\t\t)\n'
    '\t\t行.add_child(标); 行.add_child(领)\n'
    '\t\t列.add_child(行)\n'
    '\t# —— 周常差事 ——\n'
    '\tvar 周常倒计: int = max(0, (Game.上次周常日 + 7) - Game.累计游戏日)\n'
    '\tvar 周头 := Label.new(); 周头.text = "【周常】每7日刷新(距%d日)" % 周常倒计; 列.add_child(周头)\n'
    '\tif Game.当前周常.is_empty():\n'
    '\t\tvar 无 := Label.new(); 无.text = "（暂未解锁，提升门派等级后开启）"; 列.add_child(无)\n'
    '\telse:\n'
    '\t\tvar qw: Dictionary = Game.当前周常\n'
    '\t\tvar 行 := HBoxContainer.new()\n'
    '\t\tvar 标 := Label.new()\n'
    '\t\t标.text = "%s：%s（石+%s 气+%s）%s" % [qw.get("quest_name", ""), qw.get("target_desc", ""), qw.get("reward_lingjing", "0"), qw.get("reward_lingqi", "0"), "✅" if Game.周常已领 else ""]\n'
    '\t\tvar 领 := Button.new(); 领.text = "领取" if not Game.周常已领 else "已领"\n'
    '\t\t领.disabled = Game.周常已领\n'
    '\t\t领.pressed.connect(func():\n'
    '\t\t\tvar res: Dictionary = Game.领取周常()\n'
    '\t\t\t_差事提示 = res.get("msg", "")\n'
    '\t\t\t_差事面板_重建(遮)\n'
    '\t\t)\n'
    '\t\t行.add_child(标); 行.add_child(领)\n'
    '\t\t列.add_child(行)\n'
    '\tvar 一键 := Button.new(); 一键.text = "一键领取"\n'
    '\t一键.pressed.connect(func():\n'
    '\t\tvar 领了: int = 0\n'
    '\t\tfor i in Game.当前日常.size():\n'
    '\t\t\tif not Game.日常已领[i]:\n'
    '\t\t\t\tvar r: Dictionary = Game.领取日常(i)\n'
    '\t\t\t\tif r.get("ok", false): 领了 += 1\n'
    '\t\tif not Game.当前周常.is_empty() and not Game.周常已领:\n'
    '\t\t\tvar rw: Dictionary = Game.领取周常()\n'
    '\t\t\tif rw.get("ok", false): 领了 += 1\n'
    '\t\t_差事提示 = "已领取 %d 项" % 领了\n'
    '\t\t_差事面板_重建(遮)\n'
    '\t)\n'
    '\t列.add_child(一键)\n'
    '\tvar 关 := Button.new(); 关.text = "归藏"; 关.pressed.connect(func(): _差事提示 = ""; 遮.queue_free()); 列.add_child(关)\n'
    '\n'
    '# 差事面板局部重建（保留遮罩，刷新列表与提示）\n'
    'func _差事面板_重建(遮: ColorRect):\n'
    '\t_差事提示 = _差事提示\n'
    '\t遮.queue_free()\n'
    '\t_差事面板()\n',
    'func _on_差事():\n'
    '\t_建_二级页("差事")\n'
    '\n'
    'func _填_差事页(内容: Control):\n'
    '\tvar 结果 := Label.new(); 结果.text = _差事提示; 内容.add_child(结果)\n'
    '\tvar 滚 := ScrollContainer.new(); 滚.custom_minimum_size = Vector2(380, 400); 内容.add_child(滚)\n'
    '\t差事列 = VBoxContainer.new(); 滚.add_child(差事列)\n'
    '\t_刷新_差事页(结果)\n'
    '\n'
    'func _刷新_差事页(结果: Label):\n'
    '\tif 差事列 == null or not is_instance_valid(差事列):\n'
    '\t\treturn\n'
    '\tfor c in 差事列.get_children():\n'
    '\t\tc.queue_free()\n'
    '\t# —— 日常差事 ——\n'
    '\tvar 日常倒计: int = max(0, (Game.上次日常日 + 1) - Game.累计游戏日)\n'
    '\tvar 日头 := Label.new(); 日头.text = "【日常】每日刷新(距%d日) 领灵石/灵气" % 日常倒计; 差事列.add_child(日头)\n'
    '\tfor i in Game.当前日常.size():\n'
    '\t\tvar q: Dictionary = Game.当前日常[i]\n'
    '\t\tvar 已领: bool = Game.日常已领[i] if i < Game.日常已领.size() else false\n'
    '\t\tvar 行 := HBoxContainer.new()\n'
    '\t\tvar 标 := Label.new()\n'
    '\t\t标.text = "%s：%s（石+%s 气+%s）%s" % [q.get("quest_name", ""), q.get("target_desc", ""), q.get("reward_lingjing", "0"), q.get("reward_lingqi", "0"), "✅" if 已领 else ""]\n'
    '\t\tvar 领 := Button.new(); 领.text = "领取" if not 已领 else "已领"\n'
    '\t\t领.disabled = 已领\n'
    '\t\t领.pressed.connect(func():\n'
    '\t\t\tvar res: Dictionary = Game.领取日常(i)\n'
    '\t\t\t_差事提示 = res.get("msg", "")\n'
    '\t\t\t_刷新_差事页(结果)\n'
    '\t\t)\n'
    '\t\t行.add_child(标); 行.add_child(领)\n'
    '\t\t差事列.add_child(行)\n'
    '\t# —— 周常差事 ——\n'
    '\tvar 周常倒计: int = max(0, (Game.上次周常日 + 7) - Game.累计游戏日)\n'
    '\tvar 周头 := Label.new(); 周头.text = "【周常】每7日刷新(距%d日)" % 周常倒计; 差事列.add_child(周头)\n'
    '\tif Game.当前周常.is_empty():\n'
    '\t\tvar 无 := Label.new(); 无.text = "（暂未解锁，提升门派等级后开启）"; 差事列.add_child(无)\n'
    '\telse:\n'
    '\t\tvar qw: Dictionary = Game.当前周常\n'
    '\t\tvar 行 := HBoxContainer.new()\n'
    '\t\tvar 标 := Label.new()\n'
    '\t\t标.text = "%s：%s（石+%s 气+%s）%s" % [qw.get("quest_name", ""), qw.get("target_desc", ""), qw.get("reward_lingjing", "0"), qw.get("reward_lingqi", "0"), "✅" if Game.周常已领 else ""]\n'
    '\t\tvar 领 := Button.new(); 领.text = "领取" if not Game.周常已领 else "已领"\n'
    '\t\t领.disabled = Game.周常已领\n'
    '\t\t领.pressed.connect(func():\n'
    '\t\t\tvar res: Dictionary = Game.领取周常()\n'
    '\t\t\t_差事提示 = res.get("msg", "")\n'
    '\t\t\t_刷新_差事页(结果)\n'
    '\t\t)\n'
    '\t\t行.add_child(标); 行.add_child(领)\n'
    '\t\t差事列.add_child(行)\n'
    '\tvar 一键 := Button.new(); 一键.text = "一键领取"\n'
    '\t一键.pressed.connect(func():\n'
    '\t\tvar 领了: int = 0\n'
    '\t\tfor i in Game.当前日常.size():\n'
    '\t\t\tif not Game.日常已领[i]:\n'
    '\t\t\t\tvar r: Dictionary = Game.领取日常(i)\n'
    '\t\t\t\tif r.get("ok", false): 领了 += 1\n'
    '\t\tif not Game.当前周常.is_empty() and not Game.周常已领:\n'
    '\t\t\tvar rw: Dictionary = Game.领取周常()\n'
    '\t\t\tif rw.get("ok", false): 领了 += 1\n'
    '\t\t_差事提示 = "已领取 %d 项" % 领了\n'
    '\t\t_刷新_差事页(结果)\n'
    '\t)\n'
    '\t差事列.add_child(一键)\n',
    1,
))

# === _on_殿阁总览 -> 二级页 ===
reps.append((
    'func _on_殿阁总览():\n'
    '\t# 步骤①（点状态栏）改为由状态面板 gui_input Hook 推进，此处不再推进\n'
    '\t_殿阁总览弹窗()\n',
    'func _on_殿阁总览():\n'
    '\t_建_二级页("殿阁")\n',
    1,
))

# === _殿阁总览弹窗 -> _填_殿阁页 ===
reps.append((
    'func _殿阁总览弹窗():\n'
    '\tvar 遮 := ColorRect.new()\n'
    '\t遮.color = 弹窗遮罩\n'
    '\t遮.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)\n'
    '\t遮.mouse_filter = Control.MOUSE_FILTER_STOP\n'
    '\t遮.name = "殿阁总览"\n'
    '\tadd_child(遮)\n'
    '\tvar pc: PanelContainer = 新面板("—— 宗门殿阁 ——")\n'
    '\tpc.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)\n'
    '\tpc.offset_left = 20\n'
    '\tpc.offset_right = -20\n'
    '\tpc.offset_top = 50\n'
    '\tpc.offset_bottom = -20\n'
    '\t遮.add_child(pc)\n'
    '\tvar 内容: Control = pc.get_child(0)\n'
    '\t内容.add_theme_constant_override("separation", 6)\n'
    '\t内容.add_child(_玄玉占位按钮())\n'
    '\t# 山门牌匾（彩蛋钩子）：点击查看宗门立基旧事\n'
    '\tvar 牌匾 := Button.new()\n'
    '\t牌匾.text = "「太玄宗·山门」"\n'
    '\t牌匾.flat = true\n'
    '\t牌匾.add_theme_font_size_override("font_size", FONT_SUB)\n'
    '\t牌匾.add_theme_color_override("font_color", 暗金)\n'
    '\t牌匾.pressed.connect(_on_山门牌匾)\n'
    '\t内容.add_child(牌匾)\n'
    '\t# 顶部全局汇总栏（固定一屏可见）\n'
    '\t内容.add_child(_殿阁总览_汇总栏())\n'
    '\t# 分类标签导航（复用 TabBar 组件，参考离山汇总/主界面分页）\n'
    '\tvar tb := TabBar.new()\n'
    '\tfor 类别名 in 殿阁类别序:\n'
    '\t\ttb.add_tab(类别名)\n'
    '\t内容.add_child(tb)\n'
    '\t# 滚动内容区（按类别切换，替代长列表滚动）\n'
    '\tvar 滚动 := ScrollContainer.new()\n'
    '\t滚动.size_flags_vertical = Control.SIZE_EXPAND_FILL\n'
    '\t滚动.size_flags_horizontal = Control.SIZE_EXPAND_FILL\n'
    '\t内容.add_child(滚动)\n'
    '\tvar 列表列 := VBoxContainer.new()\n'
    '\t列表列.size_flags_horizontal = Control.SIZE_EXPAND_FILL\n'
    '\t列表列.add_theme_constant_override("separation", 6)\n'
    '\t滚动.add_child(列表列)\n'
    '\t_殿阁总览_填充(列表列, 殿阁类别序[0])\n'
    '\ttb.tab_changed.connect(func(idx):\n'
    '\t\t_殿阁总览_填充(列表列, 殿阁类别序[idx])\n'
    '\t)\n'
    '\t# 关闭按钮（复用现有术语与交互）\n'
    '\tvar 关 := Button.new(); 关.text = "归藏"\n'
    '\t关.pressed.connect(func(): 遮.queue_free(); 刷新())\n'
    '\t内容.add_child(关)\n',
    'func _填_殿阁页(内容: Control):\n'
    '\t内容.add_theme_constant_override("separation", 6)\n'
    '\t内容.add_child(_玄玉占位按钮())\n'
    '\t# 山门牌匾（彩蛋钩子）：点击查看宗门立基旧事\n'
    '\tvar 牌匾 := Button.new()\n'
    '\t牌匾.text = "「太玄宗·山门」"\n'
    '\t牌匾.flat = true\n'
    '\t牌匾.add_theme_font_size_override("font_size", FONT_SUB)\n'
    '\t牌匾.add_theme_color_override("font_color", 暗金)\n'
    '\t牌匾.pressed.connect(_on_山门牌匾)\n'
    '\t内容.add_child(牌匾)\n'
    '\t# 顶部全局汇总栏（固定一屏可见）\n'
    '\t内容.add_child(_殿阁总览_汇总栏())\n'
    '\t# 分类标签导航（复用 TabBar 组件，参考离山汇总/主界面分页）\n'
    '\tvar tb := TabBar.new()\n'
    '\tfor 类别名 in 殿阁类别序:\n'
    '\t\ttb.add_tab(类别名)\n'
    '\t内容.add_child(tb)\n'
    '\t# 滚动内容区（按类别切换，替代长列表滚动）\n'
    '\tvar 滚动 := ScrollContainer.new()\n'
    '\t滚动.size_flags_vertical = Control.SIZE_EXPAND_FILL\n'
    '\t滚动.size_flags_horizontal = Control.SIZE_EXPAND_FILL\n'
    '\t内容.add_child(滚动)\n'
    '\tvar 列表列 := VBoxContainer.new()\n'
    '\t列表列.size_flags_horizontal = Control.SIZE_EXPAND_FILL\n'
    '\t列表列.add_theme_constant_override("separation", 6)\n'
    '\t滚动.add_child(列表列)\n'
    '\t_殿阁总览_填充(列表列, 殿阁类别序[0])\n'
    '\ttb.tab_changed.connect(func(idx):\n'
    '\t\t_殿阁总览_填充(列表列, 殿阁类别序[idx])\n'
    '\t)\n'
    '\t刷新()\n',
    1,
))

# === _on_历练 -> 主导航切换(3) ===
reps.append((
    'func _on_历练():\n'
    '\tif Game.引导阶段 <= 4:   # 入门指引未结束：临时隐藏入门指引层，避免暗化遮罩盖住历练面板\n'
    '\t\t入门指引_层.visible = false\n'
    '\t_历练面板()\n',
    'func _on_历练():\n'
    '\t_on_主导航切换(3)\n',
    1,
))

# === 页控 -> 当前页名（页控 已废除）===
reps.append(('页控.get("纪事", null) != null and 页控["纪事"].visible',
             '当前页名 == "纪事"', 4))

# === _刷新功能解锁：增添历练 Tab 锁 + is_instance_valid 守卫 + 去掉"历练"按钮规则 ===
reps.append((
    'func _刷新功能解锁():\n'
    '\tvar 规则: Dictionary = {\n'
    '\t\t"坊市": 入门指引_坊市按钮,\n'
    '\t\t"差事": 入门指引_差事按钮,\n'
    '\t\t"历练": 入门指引_历练按钮,\n'
    '\t}\n'
    '\tfor 名 in 规则:\n'
    '\t\tvar b: Button = 规则[名]\n'
    '\t\tif b == null:\n'
    '\t\t\tcontinue\n'
    '\t\tif not _灰锁原文本.has(名):\n'
    '\t\t\t_灰锁原文本[名] = b.text\n'
    '\t\tvar 开: bool = _功能解锁(名)\n'
    '\t\tb.disabled = not 开\n'
    '\t\tif 开:\n'
    '\t\t\tb.text = _灰锁原文本[名]\n'
    '\t\t\tb.tooltip_text = ""\n'
    '\t\t\tb.modulate.a = 1.0\n'
    '\t\telse:\n'
    '\t\t\tb.text = "🔒 " + _灰锁原文本[名]\n'
    '\t\t\tb.tooltip_text = _灰锁提示(名)\n'
    '\t\t\tb.modulate.a = 0.5\n'
    '\t# 御兽 Tab 灰锁（disabled + 🔒 文字，色+形+字三通道）\n'
    '\tif 标签栏 != null:\n'
    '\t\tvar 锁: bool = not _功能解锁("御兽")\n'
    '\t\t标签栏.set_tab_disabled(2, 锁)\n'
    '\t\tif 锁:\n'
    '\t\t\t标签栏.set_tab_title(2, "🔒 御兽")\n'
    '\t\telse:\n'
    '\t\t\t标签栏.set_tab_title(2, "御兽")\n',
    'func _刷新功能解锁():\n'
    '\t# 二级页受锁入口（坊市/差事）：disabled+🔒+tooltip，点击不跳转\n'
    '\tvar 规则: Dictionary = {\n'
    '\t\t"坊市": 入门指引_坊市按钮,\n'
    '\t\t"差事": 入门指引_差事按钮,\n'
    '\t}\n'
    '\tfor 名 in 规则:\n'
    '\t\tvar b: Button = 规则[名]\n'
    '\t\tif b == null or not is_instance_valid(b):\n'
    '\t\t\tcontinue\n'
    '\t\tif not _灰锁原文本.has(名):\n'
    '\t\t\t_灰锁原文本[名] = b.text\n'
    '\t\tvar 开: bool = _功能解锁(名)\n'
    '\t\tb.disabled = not 开\n'
    '\t\tif 开:\n'
    '\t\t\tb.text = _灰锁原文本[名]\n'
    '\t\t\tb.tooltip_text = ""\n'
    '\t\t\tb.modulate.a = 1.0\n'
    '\t\telse:\n'
    '\t\t\tb.text = "🔒 " + _灰锁原文本[名]\n'
    '\t\t\tb.tooltip_text = _灰锁提示(名)\n'
    '\t\t\tb.modulate.a = 0.5\n'
    '\t# 受锁核心 Tab（御兽/历练）：disabled + 🔒 文字 + tooltip，置灰可显（§1.5）\n'
    '\tif 标签栏 != null:\n'
    '\t\tfor 名 in ["御兽", "历练"]:\n'
    '\t\t\tvar idx: int = 页名.find(名)\n'
    '\t\t\tif idx < 0:\n'
    '\t\t\t\tcontinue\n'
    '\t\t\tvar 锁: bool = not _功能解锁(名)\n'
    '\t\t\t标签栏.set_tab_disabled(idx, 锁)\n'
    '\t\t\tif 锁:\n'
    '\t\t\t\t标签栏.set_tab_title(idx, "🔒 " + 名)\n'
    '\t\t\telse:\n'
    '\t\t\t\t标签栏.set_tab_title(idx, 名)\n',
    1,
))

# === _入门指引_刷新：自动进页（_on_主导航切换），步⑤弹离山简报 ===
reps.append((
    'func _入门指引_刷新():\n'
    '\t_入门指引_清除()\n'
    '\tif Game.引导阶段 >= 1 and Game.引导阶段 <= 5:\n'
    '\t\t入门指引_跳过按钮.visible = true\n'
    '\tvar 目标: Control = null\n'
    '\tvar 文案: String = 入门指引_步骤文案.get(Game.引导阶段, "")\n'
    '\tif Game.引导阶段 == 4 and Game.弟子列表.is_empty():\n'
    '\t\t# 边缘兜底（§6.6）：理论不该发生（步③已招徒）；指向招收按钮防卡步\n'
    '\t\t目标 = 入门指引_招收按钮\n'
    '\t\t文案 = "【宗门传承指引】尚未收录弟子，先点「开启接引大典」招徒。"\n'
    '\telif Game.引导阶段 == 4:\n'
    '\t\t目标 = 列表\n'
    '\t\tif 标签栏 != null:\n'
    '\t\t\t标签栏.current_tab = 0\n'
    '\t\t_自动展开首弟子()\n'
    '\telse:\n'
    '\t\tmatch Game.引导阶段:\n'
    '\t\t\t1: 目标 = 入门指引_状态面板\n'
    '\t\t\t2: 目标 = 入门指引_推演按钮\n'
    '\t\t\t3: 目标 = 入门指引_招收按钮\n'
    '\t\t\t5: 目标 = 离山面板\n'
    '\tif 目标 != null and is_instance_valid(目标):\n'
    '\t\tif 文案.strip_edges() != "":   # 防护：空白文案不渲染气泡\n'
    '\t\t\t_入门指引_显示气泡(目标, 文案)\n'
    '\telif Game.引导阶段 >= 6:\n'
    '\t\t入门指引_跳过按钮.visible = false\n'
    '\t_刷新功能解锁()\n'
    '\t_刷新目标条()\n',
    'func _入门指引_刷新():\n'
    '\t_入门指引_清除()\n'
    '\tif Game.引导阶段 >= 1 and Game.引导阶段 <= 5:\n'
    '\t\t入门指引_跳过按钮.visible = true\n'
    '\tvar 目标: Control = null\n'
    '\tvar 文案: String = 入门指引_步骤文案.get(Game.引导阶段, "")\n'
    '\tmatch Game.引导阶段:\n'
    '\t\t1: 目标 = 入门指引_状态面板\n'
    '\t\t2: 目标 = 入门指引_推演按钮\n'
    '\t\t3:\n'
    '\t\t\t_on_主导航切换(1)   # 切到弟子页\n'
    '\t\t\t_弟子二级tab = 1     # 跳到接引 Tab\n'
    '\t\t\t_应用_弟子二级tab()\n'
    '\t\t\t目标 = 入门指引_招收按钮\n'
    '\t\t4:\n'
    '\t\t\t_on_主导航切换(1)   # 切到弟子页\n'
    '\t\t\tif Game.弟子列表.is_empty():\n'
    '\t\t\t\t目标 = 入门指引_招收按钮\n'
    '\t\t\telse:\n'
    '\t\t\t\t目标 = 列表\n'
    '\t\t\t\t_自动展开首弟子()\n'
    '\t\t5:\n'
    '\t\t\t_弹_离山简报()       # 离线收益简报弹窗\n'
    '\t\t\t目标 = 离山面板\n'
    '\tif 目标 != null and is_instance_valid(目标):\n'
    '\t\tif 文案.strip_edges() != "":   # 防护：空白文案不渲染气泡\n'
    '\t\t\t_入门指引_显示气泡(目标, 文案)\n'
    '\telif Game.引导阶段 >= 6:\n'
    '\t\t入门指引_跳过按钮.visible = false\n'
    '\t_刷新功能解锁()\n'
    '\t_刷新目标条()\n',
    1,
))

# === _招徒后高亮弟子入口：用 _on_主导航切换 替代 current_tab=0 ===
reps.append((
    'func _招徒后高亮弟子入口():\n'
    '\t_招徒后_弟子高亮中 = true\n'
    '\tif 标签栏 != null:\n'
    '\t\t标签栏.current_tab = 0   # 切到弟子页\n'
    '\tif 弟子页头 != null:\n'
    '\t\t弟子页头.modulate = 暗金   # 高亮弟子页头\n'
    '\tif 入门指引_弟子提示 != null:\n'
    '\t\t入门指引_弟子提示.visible = true   # 淡提示「可前往查看弟子详情」\n',
    'func _招徒后高亮弟子入口():\n'
    '\t_招徒后_弟子高亮中 = true\n'
    '\t_on_主导航切换(1)   # 切到弟子页（名录）\n'
    '\tif 弟子页头 != null:\n'
    '\t\t弟子页头.modulate = 暗金   # 高亮弟子页头\n'
    '\tif 入门指引_弟子提示 != null:\n'
    '\t\t入门指引_弟子提示.visible = true   # 淡提示「可前往查看弟子详情」\n',
    1,
))

# === _进入主界面 / _on_读档：上线弹离线收益简报 ===
reps.append((
    'func _进入主界面():\n'
    '\tvar 报: String = Game.推演至现在()   # 自动推演延后到此（标题屏关闭后）执行\n'
    '\t刷新()\n'
    '\t_入门指引_初始化()\n',
    'func _进入主界面():\n'
    '\tvar 报: String = Game.推演至现在()   # 自动推演延后到此（标题屏关闭后）执行\n'
    '\t刷新()\n'
    '\t_入门指引_初始化()\n'
    '\t_弹_离山简报()   # 上线自动弹离线收益简报（§1.2 B3）\n',
    1,
))
reps.append((
    'func _on_读档():\n'
    '\tGame.load_game()\n'
    '\t详情.text = "已读档"\n'
    '\t刷新()\n'
    '\t_入门指引_初始化()   # 读档后续接入门指引（按引导阶段恢复气泡/目标条/灰锁，或清场）\n',
    'func _on_读档():\n'
    '\tGame.load_game()\n'
    '\t详情.text = "已读档"\n'
    '\t刷新()\n'
    '\t_入门指引_初始化()   # 读档后续接入门指引（按引导阶段恢复气泡/目标条/灰锁，或清场）\n'
    '\t_弹_离山简报()   # 读档上线弹离线收益简报\n',
    1,
))

# === _入门指引_显示气泡：确保气泡层位于弹窗之上 ===
reps.append((
    'func _入门指引_显示气泡(目标: Control, 文案: String):\n'
    '\tif 文案.strip_edges() == "" or not is_instance_valid(目标):\n'
    '\t\treturn   # 防护：空白文案或无效目标不渲染气泡（避免空白弹窗）\n',
    'func _入门指引_显示气泡(目标: Control, 文案: String):\n'
    '\tif 文案.strip_edges() == "" or not is_instance_valid(目标):\n'
    '\t\treturn   # 防护：空白文案或无效目标不渲染气泡（避免空白弹窗）\n'
    '\tif 入门指引_层 != null and 入门指引_层.get_parent() != null:\n'
    '\t\t入门指引_层.get_parent().move_child(入门指引_层, -1)   # 确保气泡层位于弹窗之上\n',
    1,
))

# 应用
for idx, (old, new, n) in enumerate(reps):
    c = src.count(old)
    if c != n:
        sys.stderr.write("FAIL #%d: 期望 %d 次，实际 %d 次\n" % (idx, n, c))
        sys.stderr.write("---- 失败片段（前240字符）----\n")
        sys.stderr.write(old[:240] + "\n")
        sys.exit(1)
    src = src.replace(old, new)

with io.open(PATH, "w", encoding="utf-8", newline="") as f:
    f.write(src)
print("A2+B OK: 全部 %d 处替换成功，已写回 main.gd" % len(reps))
