"""Post-process UI buttons generated by ImageGen:
rembg -> optional watermark removal -> crop/fit -> deliver size.
Run after batch_generate_ui_platform.py or manual generation into png/_gen/<id>/.
"""
import argparse
import json
import os
import sys
from pathlib import Path

from PIL import Image
from rembg import remove
import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parent
GEN_DIR = PROJECT_ROOT / "png" / "_gen"
OUT_DIR = PROJECT_ROOT / "png"
REF_WM = PROJECT_ROOT / "png" / "_watermarked" / "sq_base_N.png"


def load_prompts(path: Path):
    data = json.loads(path.read_text(encoding="utf-8"))
    return data["meta"], data["prompts"]


def find_raw_file(gen_id_dir: Path) -> Path | None:
    pngs = sorted(gen_id_dir.glob("*.png"))
    for p in pngs:
        if p.name.lower() == "contact_sheet_clean.png":
            continue
        return p
    return None


def detect_watermark(a: np.ndarray) -> bool:
    h, w = a.shape[:2]
    # Use same ratios as remove_watermark.py
    RIGHT_INNER, RIGHT_OUTER = 11, 121
    BOTTOM_INNER, BOTTOM_OUTER = 11, 60
    scale = h / 1024.0
    x0 = int(w - RIGHT_OUTER * scale)
    x1 = int(w - RIGHT_INNER * scale)
    y0 = int(h - BOTTOM_OUTER * scale)
    y1 = int(h - BOTTOM_INNER * scale)
    x0, x1 = max(0, x0), min(w, x1)
    y0, y1 = max(0, y0), min(h, y1)
    if x1 <= x0 or y1 <= y0:
        return False
    roi = a[y0:y1, x0:x1]
    nontrans = roi[:, :, 3] > 30
    bright = roi[:, :, :3].mean(axis=2) > 120
    bright_nontrans = (bright & nontrans).sum()
    total = nontrans.sum()
    if total == 0:
        return False
    ratio = bright_nontrans / total
    return ratio > 0.15 and bright_nontrans > 20


def remove_watermark_from_image(img: Image.Image, mask_ref: np.ndarray) -> Image.Image:
    import cv2
    arr = np.array(img.convert("RGBA"))
    h, w = arr.shape[:2]
    h_ref, w_ref = 1024, 1024
    scale = h / h_ref
    RIGHT_INNER, RIGHT_OUTER = 11, 121
    BOTTOM_INNER, BOTTOM_OUTER = 11, 60
    x0 = int(w - RIGHT_OUTER * scale)
    x1 = int(w - RIGHT_INNER * scale)
    y0 = int(h - BOTTOM_OUTER * scale)
    y1 = int(h - BOTTOM_INNER * scale)
    x0, x1 = max(0, x0), min(w, x1)
    y0, y1 = max(0, y0), min(h, y1)
    roi_w, roi_h = x1 - x0, y1 - y0
    if roi_w <= 0 or roi_h <= 0:
        return img
    mask_resized = cv2.resize(mask_ref, (roi_w, roi_h), interpolation=cv2.INTER_NEAREST)
    kernel = np.ones((17, 17), np.uint8)
    mask_dilated = cv2.dilate(mask_resized, kernel, iterations=1)
    roi_rgb = arr[y0:y1, x0:x1, :3]
    inpainted = cv2.inpaint(roi_rgb, mask_dilated, 8, cv2.INPAINT_TELEA)
    arr[y0:y1, x0:x1, :3] = inpainted
    return Image.fromarray(arr, "RGBA")


def extract_reference_mask(ref_path: Path) -> np.ndarray:
    import cv2
    ref = np.array(Image.open(ref_path).convert("RGBA"))
    h_ref, w_ref = ref.shape[:2]
    RIGHT_INNER, RIGHT_OUTER = 11, 121
    BOTTOM_INNER, BOTTOM_OUTER = 11, 60
    x0r = w_ref - RIGHT_OUTER - 10
    x1r = w_ref - RIGHT_INNER + 10
    y0r = h_ref - BOTTOM_OUTER - 10
    y1r = h_ref - BOTTOM_INNER + 10
    roi_ref = ref[y0r:y1r, x0r:x1r]
    gray_ref = cv2.cvtColor(roi_ref[:, :, :3], cv2.COLOR_RGB2GRAY)
    med = np.median(gray_ref)
    mask_ref = (gray_ref.astype(np.float32) - med) > 22
    return (mask_ref.astype(np.uint8)) * 255


def fit_crop(im: Image.Image, shape: str, deliver_size: tuple[int, int]) -> Image.Image:
    a = np.array(im)
    h, w = a.shape[:2]
    mask = a[:, :, 3] > 30
    ys, xs = np.where(mask)
    if len(xs) == 0:
        # fallback: center crop to target aspect
        tw, th = deliver_size
        target_aspect = tw / th
        if w / h > target_aspect:
            new_w = int(h * target_aspect)
            x0 = (w - new_w) // 2
            return im.crop((x0, 0, x0 + new_w, h)).resize(deliver_size, Image.Resampling.LANCZOS)
        else:
            new_h = int(w / target_aspect)
            y0 = (h - new_h) // 2
            return im.crop((0, y0, w, y0 + new_h)).resize(deliver_size, Image.Resampling.LANCZOS)

    x0, x1 = int(xs.min()), int(xs.max()) + 1
    y0, y1 = int(ys.min()), int(ys.max()) + 1

    # add 2% padding
    pad = int(max(w, h) * 0.02)
    x0 = max(0, x0 - pad)
    y0 = max(0, y0 - pad)
    x1 = min(w, x1 + pad)
    y1 = min(h, y1 + pad)

    tw, th = deliver_size
    target_aspect = tw / th
    cw = x1 - x0
    ch = y1 - y0
    actual_aspect = cw / ch

    if actual_aspect > target_aspect:
        # too wide: crop width
        new_cw = int(ch * target_aspect)
        cx = (x0 + x1) // 2
        x0 = max(0, cx - new_cw // 2)
        x1 = min(w, x0 + new_cw)
        if x1 - x0 < new_cw:
            x0 = max(0, x1 - new_cw)
    else:
        # too tall: crop height
        new_ch = int(cw / target_aspect)
        cy = (y0 + y1) // 2
        y0 = max(0, cy - new_ch // 2)
        y1 = min(h, y0 + new_ch)
        if y1 - y0 < new_ch:
            y0 = max(0, y1 - new_ch)

    cropped = im.crop((x0, y0, x1, y1))
    return cropped.resize(deliver_size, Image.Resampling.LANCZOS)


def process_one(item: dict, mask_ref: np.ndarray | None, force: bool = False) -> bool:
    gid = item["id"]
    shape = item["shape"]
    deliver_size = (256, 256) if shape == "square" else (512, 128)

    out_path = OUT_DIR / f"{gid}.png"
    if out_path.exists() and not force:
        print(f"[skip] {gid} already exists")
        return True

    gen_id_dir = GEN_DIR / gid
    raw_path = find_raw_file(gen_id_dir)
    if raw_path is None:
        print(f"[fail] {gid}: no generated PNG in {gen_id_dir}", file=sys.stderr)
        return False

    try:
        img = Image.open(raw_path).convert("RGBA")
    except Exception as e:
        print(f"[fail] {gid}: cannot open {raw_path}: {e}", file=sys.stderr)
        return False

    # rembg expects RGB; output is RGBA
    rgb = Image.new("RGB", img.size, (128, 128, 128))
    rgb.paste(img, mask=img.split()[3] if img.mode == "RGBA" else None)
    rgba = remove(rgb)

    if detect_watermark(np.array(rgba)) and mask_ref is not None:
        rgba = remove_watermark_from_image(rgba, mask_ref)

    final = fit_crop(rgba, shape, deliver_size)
    final.save(out_path)
    print(f"[ok] {gid} -> {out_path} ({deliver_size[0]}x{deliver_size[1]})")
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", default=str(PROJECT_ROOT / "prompts_ui_regen.json"))
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--ids", help="comma-separated ids, default all")
    args = ap.parse_args()

    meta, prompts = load_prompts(Path(args.source))
    if args.ids:
        wanted = set(args.ids.split(","))
        prompts = [p for p in prompts if p["id"] in wanted]

    mask_ref = None
    if REF_WM.exists():
        try:
            mask_ref = extract_reference_mask(REF_WM)
            print(f"[info] watermark reference mask loaded from {REF_WM}")
        except Exception as e:
            print(f"[warn] cannot load watermark reference: {e}", file=sys.stderr)

    ok = fail = 0
    for item in prompts:
        if process_one(item, mask_ref, args.force):
            ok += 1
        else:
            fail += 1
    print(f"\nDone: {ok} ok, {fail} fail")
    sys.exit(0 if fail == 0 else 1)


if __name__ == "__main__":
    main()
